/**
 * 🦊 Generated Vitest Configuration
 * Auto-generated from project architecture on 2025-09-21T09:53:29.775Z
 *
 * This file is generated by the vitest-config-generator tool.
 * Do not edit manually - regenerate using: pnpm generate-vitest-config
 */

import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    maxWorkers: 1,
    pool: "forks",
    poolOptions: {
      forks: {
        maxForks: 1,
        singleFork: true,
      },
    },
    fileParallelism: false,
    isolate: false,
    testTimeout: 30000,
    hookTimeout: 10000,
    reporters: [
      [
        "default",
        {
          summary: false,
        },
      ],
      [
        "json",
        {
          outputFile: ".vitest-reports/global-report.json",
        },
      ],
    ],
    coverage: {
      provider: "v8",
      reporter: ["text", "json", "html"],
      reportsDirectory: ".vitest-coverage/global",
    },
    environment: "happy-dom",
    globals: true,
    fakeTimers: {
      toFake: [
        "setTimeout",
        "clearTimeout",
        "setInterval",
        "clearInterval",
        "setImmediate",
        "clearImmediate",
        "performance",
        "Date",
        "requestAnimationFrame",
        "cancelAnimationFrame",
        "requestIdleCallback",
        "cancelIdleCallback",
      ],
      advanceTimers: true,
      now: 0,
    },
    include: [
      "**/*.{test,spec}.{js,ts,tsx}",
      "**/__tests__/**/*.{js,ts,tsx}",
      "src/**/*.{test,spec}.{js,ts,tsx}",
      "src/__tests__/**/*.{js,ts,tsx}",
    ],
    exclude: [
      "node_modules",
      "**/node_modules/**",
      "dist",
      ".git",
      ".cache",
      "coverage",
      ".vitest-reports",
      ".vitest-coverage",
      "**/node_modules/**/*.{test,spec}.{js,ts,tsx}",
      "**/node_modules/**",
      "**/dist/**",
      "**/build/**",
      "**/coverage/**",
      "**/.git/**",
      "**/third_party/**",
      "**/.vitest/**",
      "**/temp/**",
      "**/tmp/**",
    ],
    projects: [],
  },
  resolve: {
    conditions: ["development", "browser"],
  },
});
