/**
 * 🦊 Generated Vitest Configuration
 * Auto-generated from project architecture on 2025-09-21T08:34:57.643Z
 *
 * This file is generated by the vitest-config-generator tool.
 * Do not edit manually - regenerate using: pnpm generate-vitest-config
 */

import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    maxWorkers: 1,
    pool: "forks",
    poolOptions: {
      forks: {
        maxForks: 1,
        singleFork: true,
      },
    },
    fileParallelism: false,
    isolate: false,
    testTimeout: 30000,
    hookTimeout: 10000,
    reporters: [
      [
        "default",
        {
          summary: false,
        },
      ],
      [
        "json",
        {
          outputFile: ".vitest-reports/global-report.json",
        },
      ],
    ],
    coverage: {
      provider: "v8",
      reporter: ["text", "json", "html"],
      reportsDirectory: ".vitest-coverage/global",
    },
    environment: "happy-dom",
    globals: true,
    fakeTimers: {
      toFake: [
        "setTimeout",
        "clearTimeout",
        "setInterval",
        "clearInterval",
        "setImmediate",
        "clearImmediate",
        "performance",
        "Date",
        "requestAnimationFrame",
        "cancelAnimationFrame",
        "requestIdleCallback",
        "cancelIdleCallback",
      ],
      advanceTimers: true,
      now: 0,
    },
    include: [
      "**/*.{test,spec}.{js,ts,tsx}",
      "**/__tests__/**/*.{js,ts,tsx}",
      "src/**/*.{test,spec}.{js,ts,tsx}",
      "src/__tests__/**/*.{js,ts,tsx}",
    ],
    exclude: [
      "node_modules",
      "**/node_modules/**",
      "dist",
      ".git",
      ".cache",
      "coverage",
      ".vitest-reports",
      ".vitest-coverage",
      "**/node_modules/**/*.{test,spec}.{js,ts,tsx}",
      "**/node_modules/**",
      "**/dist/**",
      "**/build/**",
      "**/coverage/**",
      "**/.git/**",
      "**/third_party/**",
      "**/.vitest/**",
      "**/temp/**",
      "**/tmp/**",
    ],
    projects: [
      {
        name: "packages/ai/ai-shared",
        root: "./packages/ai/ai-shared",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ai/annotating-core",
        root: "./packages/ai/annotating-core",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ai/annotating-florence2",
        root: "./packages/ai/annotating-florence2",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ai/annotating-joy",
        root: "./packages/ai/annotating-joy",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ai/annotating-jtp2",
        root: "./packages/ai/annotating-jtp2",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ai/annotating-ui",
        root: "./packages/ai/annotating-ui",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ai/annotating-wdv3",
        root: "./packages/ai/annotating-wdv3",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ai/caption",
        root: "./packages/ai/caption",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ai/caption-core",
        root: "./packages/ai/caption-core",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ai/caption-multimodal",
        root: "./packages/ai/caption-multimodal",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ai/caption-ui",
        root: "./packages/ai/caption-ui",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ai/comfy",
        root: "./packages/ai/comfy",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ai/model-management",
        root: "./packages/ai/model-management",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ai/multimodal",
        root: "./packages/ai/multimodal",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ai/nlweb",
        root: "./packages/ai/nlweb",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ai/rag",
        root: "./packages/ai/rag",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ai/tool-calling",
        root: "./packages/ai/tool-calling",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/algorithms/algorithms",
        root: "./packages/algorithms/algorithms",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/core/composables",
        root: "./packages/core/composables",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/core/config",
        root: "./packages/core/config",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/core/connection",
        root: "./packages/core/connection",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/core/core",
        root: "./packages/core/core",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/core/features",
        root: "./packages/core/features",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/core/i18n",
        root: "./packages/core/i18n",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/core/settings",
        root: "./packages/core/settings",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/core/testing",
        root: "./packages/core/testing",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/core/validation",
        root: "./packages/core/validation",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/data/file-processing",
        root: "./packages/data/file-processing",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/data/repository-core",
        root: "./packages/data/repository-core",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/data/repository-multimodal",
        root: "./packages/data/repository-multimodal",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/data/repository-search",
        root: "./packages/data/repository-search",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/data/repository-storage",
        root: "./packages/data/repository-storage",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/data/scraping",
        root: "./packages/data/scraping",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/data/unified-repository",
        root: "./packages/data/unified-repository",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/dev-tools/adr-system",
        root: "./packages/dev-tools/adr-system",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/dev-tools/code-quality",
        root: "./packages/dev-tools/code-quality",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/dev-tools/dev-server-management",
        root: "./packages/dev-tools/dev-server-management",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/dev-tools/git-automation",
        root: "./packages/dev-tools/git-automation",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/dev-tools/humility-parser",
        root: "./packages/dev-tools/humility-parser",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/dev-tools/project-architecture",
        root: "./packages/dev-tools/project-architecture",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/dev-tools/queue-watcher",
        root: "./packages/dev-tools/queue-watcher",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/docs/diagram-generator",
        root: "./packages/docs/diagram-generator",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/docs/docs-components",
        root: "./packages/docs/docs-components",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/docs/docs-core",
        root: "./packages/docs/docs-core",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/docs/docs-generator",
        root: "./packages/docs/docs-generator",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/docs/docs-site",
        root: "./packages/docs/docs-site",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/media/3d",
        root: "./packages/media/3d",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/media/audio",
        root: "./packages/media/audio",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/media/boundingbox",
        root: "./packages/media/boundingbox",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/media/gallery",
        root: "./packages/media/gallery",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/media/gallery-ai",
        root: "./packages/media/gallery-ai",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/media/gallery-dl",
        root: "./packages/media/gallery-dl",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/media/image",
        root: "./packages/media/image",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/media/segmentation",
        root: "./packages/media/segmentation",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/media/video",
        root: "./packages/media/video",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/services/api-client",
        root: "./packages/services/api-client",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/services/api-client/src/generated",
        root: "./packages/services/api-client/src/generated",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/services/auth",
        root: "./packages/services/auth",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/services/chat",
        root: "./packages/services/chat",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/services/email",
        root: "./packages/services/email",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/services/service-manager",
        root: "./packages/services/service-manager",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ui/animation",
        root: "./packages/ui/animation",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ui/charts",
        root: "./packages/ui/charts",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ui/colors",
        root: "./packages/ui/colors",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ui/components-charts",
        root: "./packages/ui/components-charts",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ui/components-core",
        root: "./packages/ui/components-core",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ui/components-dashboard",
        root: "./packages/ui/components-dashboard",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ui/components-themes",
        root: "./packages/ui/components-themes",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ui/components-utils",
        root: "./packages/ui/components-utils",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ui/dashboard",
        root: "./packages/ui/dashboard",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ui/error-boundaries",
        root: "./packages/ui/error-boundaries",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ui/floating-panel",
        root: "./packages/ui/floating-panel",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ui/fluent-icons",
        root: "./packages/ui/fluent-icons",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ui/games",
        root: "./packages/ui/games",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ui/games/src/ecs/experiments/simd",
        root: "./packages/ui/games/src/ecs/experiments/simd",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ui/games/src/ecs/experiments/simd/pkg",
        root: "./packages/ui/games/src/ecs/experiments/simd/pkg",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ui/monaco",
        root: "./packages/ui/monaco",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ui/themes",
        root: "./packages/ui/themes",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "packages/ui/ui",
        root: "./packages/ui/ui",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "examples/3d-demo",
        root: "./examples/3d-demo",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "examples/algo-bench",
        root: "./examples/algo-bench",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "examples/auth-app",
        root: "./examples/auth-app",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "examples/basic-app",
        root: "./examples/basic-app",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "examples/clock",
        root: "./examples/clock",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "examples/comfy-demo",
        root: "./examples/comfy-demo",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "examples/comprehensive-dashboard",
        root: "./examples/comprehensive-dashboard",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "examples/ecs-agent-tracker",
        root: "./examples/ecs-agent-tracker",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "examples/email-app",
        root: "./examples/email-app",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "examples/embedding-visualization-demo",
        root: "./examples/embedding-visualization-demo",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "examples/error-demo",
        root: "./examples/error-demo",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "examples/features-app",
        root: "./examples/features-app",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "examples/file-test",
        root: "./examples/file-test",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "examples/hue-shifting-demo",
        root: "./examples/hue-shifting-demo",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "examples/i18n-demo",
        root: "./examples/i18n-demo",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "examples/icons-demo",
        root: "./examples/icons-demo",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "examples/image-caption-app",
        root: "./examples/image-caption-app",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "examples/multi-theme",
        root: "./examples/multi-theme",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "examples/prompt-note",
        root: "./examples/prompt-note",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "examples/rag-demo",
        root: "./examples/rag-demo",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "examples/test-app",
        root: "./examples/test-app",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "examples/tutorial-app",
        root: "./examples/tutorial-app",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
      {
        name: "templates/starter",
        root: "./templates/starter",
        test: {
          setupFiles: ["./src/__tests__/setup.ts"],
          include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
          exclude: ["node_modules", "dist", "build", "coverage", "node_modules", "dist", "build", "coverage"],
          environment: "happy-dom",
          coverage: {
            thresholds: {
              global: {
                branches: 80,
                functions: 85,
                lines: 85,
                statements: 85,
              },
            },
          },
        },
      },
    ],
  },
  resolve: {
    conditions: ["development", "browser"],
  },
});
