# Generated race data for Alembic migration
spirits_data = [
        {
            'id': str(uuid.uuid4()),
            'name': 'alien',
            'category': 'extraterrestrial_and_cosmic',
            'description': 'Otherworldly beings with advanced technology and cosmic awareness',
            'emoji': '👽',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [7, 14, 21, 28, 35, 42, 49],
            'traits': ['otherworldly', 'advanced', 'cosmic', 'mysterious', 'intelligent'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'ant',
            'category': 'insects_and_arachnids',
            'description': 'Social insects known for their cooperation and strength',
            'emoji': '🐜',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [1, 2, 3, 4, 5, 6, 7],
            'traits': ['cooperative', 'strong', 'social', 'organized', 'persistent'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'ape',
            'category': 'primates_and_intelligence',
            'description': 'Intelligent primates known for their tool use and social complexity',
            'emoji': '🦍',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [11, 22, 33, 44, 55, 66, 77],
            'traits': ['intelligent', 'tool-using', 'social', 'complex', 'strong'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'axolotl',
            'category': 'aquatic_and_marine',
            'description': 'Regenerative amphibians known for their healing abilities and uniqueness',
            'emoji': '🦎',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [1, 2, 3, 4, 5, 6, 7],
            'traits': ['regenerative', 'healing', 'unique', 'resilient', 'mystical'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'aye',
            'category': 'exotic_and_unique',
            'description': 'Nocturnal lemurs known for their unique appearance and behavior',
            'emoji': '🦝',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [1, 2, 3, 4, 5, 6, 7],
            'traits': ['nocturnal', 'unique', 'lemur', 'endangered', 'mysterious'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'bear',
            'category': 'bears_and_large_mammals',
            'description': 'Powerful omnivores known for their strength and seasonal wisdom',
            'emoji': '🐻',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [10, 20, 30, 40, 50, 60, 70],
            'traits': ['powerful', 'strong', 'seasonal', 'protective', 'wise'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'bee',
            'category': 'insects_and_arachnids',
            'description': 'Pollinating insects known for their industry and community',
            'emoji': '🐝',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [6, 12, 18, 24, 30, 36, 42],
            'traits': ['industrious', 'community', 'pollinating', 'honey', 'organized'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'capybara',
            'category': 'exotic_and_unique',
            'description': 'Giant rodents known for their calm nature and social behavior',
            'emoji': '🐹',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [1, 2, 3, 4, 5, 6, 7],
            'traits': ['calm', 'social', 'giant', 'rodent', 'peaceful'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'cheetah',
            'category': 'big_cats_and_predators',
            'description': 'Fastest land animals known for their speed and grace',
            'emoji': '🐆',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [4, 8, 12, 16, 20, 24, 28],
            'traits': ['fast', 'graceful', 'speed', 'agile', 'focused'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'coyote',
            'category': 'canines_and_foxes',
            'description': 'Adaptable canines known for their resourcefulness and survival skills',
            'emoji': '🐺',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [4, 8, 12, 16, 20, 24, 28],
            'traits': ['adaptable', 'resourceful', 'survivor', 'clever', 'independent'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'dolphin',
            'category': 'aquatic_and_marine',
            'description': 'Intelligent marine mammals known for communication and social behavior',
            'emoji': '🐬',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [6, 12, 18, 24, 30, 36, 42],
            'traits': ['intelligent', 'social', 'communicative', 'playful', 'cooperative'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'dragon',
            'category': 'mythical_and_legendary',
            'description': 'Ancient, powerful creatures with elemental mastery and legendary wisdom',
            'emoji': '🐉',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [9, 18, 27, 36, 45, 54, 63],
            'traits': ['ancient', 'powerful', 'elemental', 'wise', 'legendary'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'dragonfly',
            'category': 'insects_and_arachnids',
            'description': 'Agile flying insects known for their speed and precision',
            'emoji': '🦟',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [2, 4, 6, 8, 10, 12, 14],
            'traits': ['agile', 'fast', 'precise', 'flying', 'predatory'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'eagle',
            'category': 'birds_of_prey_and_flight',
            'description': 'Majestic birds of prey known for their vision and leadership',
            'emoji': '🦅',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [12, 24, 36, 48, 60, 72, 84],
            'traits': ['visionary', 'leadership', 'majestic', 'focused', 'soaring'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'elephant',
            'category': 'bears_and_large_mammals',
            'description': 'Wise giants known for their memory and family bonds',
            'emoji': '🐘',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [15, 30, 45, 60, 75, 90, 105],
            'traits': ['wise', 'memory', 'family', 'gentle', 'ancient'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'falcon',
            'category': 'birds_of_prey_and_flight',
            'description': 'Swift birds of prey known for their speed and precision',
            'emoji': '🦅',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [3, 6, 9, 12, 15, 18, 21],
            'traits': ['swift', 'precise', 'focused', 'fast', 'accurate'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'flamingo',
            'category': 'exotic_and_unique',
            'description': 'Pink wading birds known for their elegance and balance',
            'emoji': '🦩',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [1, 2, 3, 4, 5, 6, 7],
            'traits': ['elegant', 'balanced', 'pink', 'wading', 'social'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'fox',
            'category': 'canines_and_foxes',
            'description': 'Cunning and intelligent canines known for their strategic thinking and adaptability',
            'emoji': '🦊',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [3, 7, 13, 21, 34, 55, 89],
            'traits': ['cunning', 'intelligent', 'adaptable', 'strategic', 'graceful'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'frog',
            'category': 'reptiles_and_amphibians',
            'description': 'Amphibious creatures known for their transformation and adaptability',
            'emoji': '🐸',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [3, 6, 9, 12, 15, 18, 21],
            'traits': ['transformative', 'adaptable', 'amphibious', 'vocal', 'colorful'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'hawk',
            'category': 'birds_of_prey_and_flight',
            'description': 'Sharp-eyed birds of prey known for their focus and determination',
            'emoji': '🦅',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [9, 18, 27, 36, 45, 54, 63],
            'traits': ['focused', 'determined', 'sharp-eyed', 'agile', 'persistent'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'jackal',
            'category': 'canines_and_foxes',
            'description': 'Opportunistic canines known for their stealth and cunning',
            'emoji': '🐺',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [5, 10, 15, 20, 25, 30, 35],
            'traits': ['stealthy', 'opportunistic', 'cunning', 'nocturnal', 'persistent'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'jaguar',
            'category': 'big_cats_and_predators',
            'description': 'Powerful big cats known for their strength and swimming ability',
            'emoji': '🐆',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [6, 12, 18, 24, 30, 36, 42],
            'traits': ['powerful', 'aquatic', 'strong', 'territorial', 'fierce'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'kiwi',
            'category': 'exotic_and_unique',
            'description': 'Flightless birds known for their uniqueness and national symbol status',
            'emoji': '🐦',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [1, 2, 3, 4, 5, 6, 7],
            'traits': ['flightless', 'unique', 'national', 'nocturnal', 'endemic'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'lemur',
            'category': 'primates_and_intelligence',
            'description': 'Unique primates known for their diversity and island adaptation',
            'emoji': '🦝',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [4, 8, 12, 16, 20, 24, 28],
            'traits': ['unique', 'diverse', 'island', 'nocturnal', 'endemic'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'leopard',
            'category': 'big_cats_and_predators',
            'description': 'Stealthy big cats known for their agility and camouflage',
            'emoji': '🐆',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [7, 14, 21, 28, 35, 42, 49],
            'traits': ['stealthy', 'agile', 'camouflaged', 'patient', 'adaptable'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'lion',
            'category': 'big_cats_and_predators',
            'description': 'Majestic big cats known for their leadership and pride',
            'emoji': '🦁',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [1, 2, 3, 5, 8, 13, 21],
            'traits': ['leadership', 'pride', 'majestic', 'bold', 'protective'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'lizard',
            'category': 'reptiles_and_amphibians',
            'description': 'Adaptable reptiles known for their regeneration and diversity',
            'emoji': '🦎',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [5, 10, 15, 20, 25, 30, 35],
            'traits': ['adaptable', 'regenerative', 'diverse', 'scaled', 'ancient'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'lynx',
            'category': 'big_cats_and_predators',
            'description': 'Stealthy wild cats known for their tufted ears and hunting skills',
            'emoji': '🐱',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [5, 10, 15, 20, 25, 30, 35],
            'traits': ['stealthy', 'hunting', 'tufted', 'mountain', 'solitary'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'mantis',
            'category': 'insects_and_arachnids',
            'description': 'Praying insects known for their patience and precision strikes',
            'emoji': '🦗',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [4, 8, 12, 16, 20, 24, 28],
            'traits': ['patient', 'precise', 'praying', 'stealthy', 'focused'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'monkey',
            'category': 'primates_and_intelligence',
            'description': 'Agile primates known for their curiosity and social behavior',
            'emoji': '🐵',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [6, 12, 18, 24, 30, 36, 42],
            'traits': ['agile', 'curious', 'social', 'playful', 'adaptable'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'narwhal',
            'category': 'exotic_and_unique',
            'description': 'Arctic unicorns of the sea known for their mystical tusks',
            'emoji': '🦄',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [1, 2, 3, 4, 5, 6, 7],
            'traits': ['mystical', 'arctic', 'unicorn', 'tusked', 'mysterious'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'octopus',
            'category': 'aquatic_and_marine',
            'description': 'Intelligent cephalopods known for their problem-solving and adaptability',
            'emoji': '🐙',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [8, 16, 24, 32, 40, 48, 56],
            'traits': ['intelligent', 'adaptable', 'problem-solver', 'flexible', 'mysterious'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'otter',
            'category': 'aquatic_and_marine',
            'description': 'Playful aquatic mammals known for their joy and thoroughness',
            'emoji': '🦦',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [5, 10, 15, 20, 25, 30, 35],
            'traits': ['playful', 'thorough', 'joyful', 'aquatic', 'social'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'owl',
            'category': 'birds_of_prey_and_flight',
            'description': 'Nocturnal birds of prey known for their wisdom and stealth',
            'emoji': '🦉',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [11, 22, 33, 44, 55, 66, 77],
            'traits': ['wise', 'nocturnal', 'stealthy', 'patient', 'observant'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'panda',
            'category': 'bears_and_large_mammals',
            'description': 'Gentle giants known for their peaceful nature and bamboo diet',
            'emoji': '🐼',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [1, 2, 3, 4, 5, 6, 7],
            'traits': ['gentle', 'peaceful', 'bamboo', 'endangered', 'calm'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'pangolin',
            'category': 'exotic_and_unique',
            'description': 'Scaly anteaters known for their unique armor and rarity',
            'emoji': '🦎',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [1, 2, 3, 4, 5, 6, 7],
            'traits': ['unique', 'armored', 'scaled', 'rare', 'endangered'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'peacock',
            'category': 'exotic_and_unique',
            'description': 'Majestic birds known for their stunning displays and beauty',
            'emoji': '🦚',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [1, 2, 3, 4, 5, 6, 7],
            'traits': ['majestic', 'beautiful', 'displaying', 'colorful', 'proud'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'phoenix',
            'category': 'mythical_and_legendary',
            'description': 'Mythical firebirds known for rebirth, renewal, and eternal cycles',
            'emoji': '🔥',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [14, 28, 42, 56, 70, 84, 98],
            'traits': ['rebirth', 'renewal', 'eternal', 'cycles', 'transformation'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'platypus',
            'category': 'exotic_and_unique',
            'description': 'Unique monotremes known for their bizarre combination of traits',
            'emoji': '🦆',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [1, 2, 3, 4, 5, 6, 7],
            'traits': ['unique', 'bizarre', 'monotreme', 'venomous', 'aquatic'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'quokka',
            'category': 'exotic_and_unique',
            'description': 'Happy marsupials known for their perpetual smile and friendliness',
            'emoji': '🐨',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [1, 2, 3, 4, 5, 6, 7],
            'traits': ['happy', 'friendly', 'smiling', 'marsupial', 'endemic'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'raven',
            'category': 'birds_of_prey_and_flight',
            'description': 'Intelligent corvids known for their wisdom and mystery',
            'emoji': '🐦‍⬛',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [13, 26, 39, 52, 65, 78, 91],
            'traits': ['wise', 'mysterious', 'intelligent', 'observant', 'symbolic'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'rhino',
            'category': 'bears_and_large_mammals',
            'description': 'Armored giants known for their strength and territorial nature',
            'emoji': '🦏',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [8, 16, 24, 32, 40, 48, 56],
            'traits': ['armored', 'strong', 'territorial', 'endangered', 'powerful'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'shark',
            'category': 'aquatic_and_marine',
            'description': 'Apex predators of the sea known for their efficiency and focus',
            'emoji': '🦈',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [2, 4, 6, 8, 10, 12, 14],
            'traits': ['efficient', 'focused', 'predatory', 'streamlined', 'relentless'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'snake',
            'category': 'reptiles_and_amphibians',
            'description': 'Serpentine reptiles known for their patience and transformation',
            'emoji': '🐍',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [7, 14, 21, 28, 35, 42, 49],
            'traits': ['patient', 'transformative', 'serpentine', 'mysterious', 'renewal'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'spider',
            'category': 'insects_and_arachnids',
            'description': 'Web-weaving arachnids known for their patience and precision',
            'emoji': '🕷️',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [8, 16, 24, 32, 40, 48, 56],
            'traits': ['patient', 'precise', 'web-weaving', 'eight-legged', 'strategic'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'tiger',
            'category': 'big_cats_and_predators',
            'description': 'Powerful big cats known for their strength and ferocity',
            'emoji': '🐅',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [9, 18, 27, 36, 45, 54, 63],
            'traits': ['powerful', 'ferocious', 'strong', 'independent', 'fierce'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'toucan',
            'category': 'exotic_and_unique',
            'description': 'Colorful birds known for their distinctive beaks and tropical habitat',
            'emoji': '🦜',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [1, 2, 3, 4, 5, 6, 7],
            'traits': ['colorful', 'tropical', 'beaked', 'bright', 'social'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'turtle',
            'category': 'reptiles_and_amphibians',
            'description': 'Ancient reptiles known for their longevity and wisdom',
            'emoji': '🐢',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [20, 40, 60, 80, 100, 120, 140],
            'traits': ['ancient', 'long-lived', 'wise', 'patient', 'protective'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'whale',
            'category': 'aquatic_and_marine',
            'description': 'Majestic marine giants known for their wisdom and depth',
            'emoji': '🐋',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [7, 14, 21, 28, 35, 42, 49],
            'traits': ['wise', 'majestic', 'deep', 'ancient', 'powerful'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'wolf',
            'category': 'canines_and_foxes',
            'description': 'Pack-oriented canines known for loyalty, coordination, and protective instincts',
            'emoji': '🐺',
            'enabled': True,
            'weight': 1.0,
            'generation_numbers': [8, 16, 24, 32, 40, 48, 56],
            'traits': ['loyal', 'protective', 'coordinated', 'fierce', 'pack-oriented'],
            'base_names': [],
            'custom_data': {},
            'created_at': now,
            'updated_at': now
        }
]
