/**
 * Caption Type Definitions
 *
 * Defines the types of captions that can be generated by Reynard's
 * caption generation system. Self-contained type definitions that
 * replace Yipyap's caption type system.
 */
export declare enum CaptionType {
    CAPTION = "caption",
    TAGS = "tags",
    E621 = "e621",
    TOML = "toml"
}
export interface CaptionTypeInfo {
    type: CaptionType;
    extension: string;
    description: string;
    mimeType: string;
    supportsMetadata: boolean;
}
export declare const CAPTION_TYPE_INFO: Record<CaptionType, CaptionTypeInfo>;
export declare function getCaptionTypeInfo(type: CaptionType): CaptionTypeInfo;
export declare function getCaptionExtension(type: CaptionType): string;
export declare function getCaptionMimeType(type: CaptionType): string;
export declare function isMetadataSupported(type: CaptionType): boolean;
export declare function fromExtension(extension: string): CaptionType | undefined;
