"""Re-enable AIMetadata relationships

Revision ID: 755416c2fdcb
Revises: c88a9f42e7fc
Create Date: 2025-09-26 10:35:16.163957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755416c2fdcb'
down_revision = 'c88a9f42e7fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
