"""Fix AIMetadata relationships

Revision ID: c88a9f42e7fc
Revises: 587157f154aa
Create Date: 2025-09-26 10:29:54.415765

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c88a9f42e7fc'
down_revision = '587157f154aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
