"""Add naming configuration tables

Revision ID: 183c8980160f
Revises: 1677ed29f643
Create Date: 2025-09-20 21:08:54.963155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '183c8980160f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('naming_components',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('component_type', sa.String(length=100), nullable=False),
    sa.Column('component_name', sa.String(length=100), nullable=False),
    sa.Column('component_value', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('component_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_type', 'component_name', name='uq_component_type_name')
    )
    op.create_index(op.f('ix_naming_components_component_type'), 'naming_components', ['component_type'], unique=False)
    op.create_table('naming_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_naming_config_config_key'), 'naming_config', ['config_key'], unique=True)
    op.create_table('naming_spirits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('generation_numbers', sa.JSON(), nullable=False),
    sa.Column('traits', sa.JSON(), nullable=False),
    sa.Column('base_names', sa.JSON(), nullable=False),
    sa.Column('custom_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_naming_spirits_enabled'), 'naming_spirits', ['enabled'], unique=False)
    op.create_index(op.f('ix_naming_spirits_name'), 'naming_spirits', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_naming_spirits_name'), table_name='naming_spirits')
    op.drop_index(op.f('ix_naming_spirits_enabled'), table_name='naming_spirits')
    op.drop_table('naming_spirits')
    op.drop_index(op.f('ix_naming_config_config_key'), table_name='naming_config')
    op.drop_table('naming_config')
    op.drop_index(op.f('ix_naming_components_component_type'), table_name='naming_components')
    op.drop_table('naming_components')
    # ### end Alembic commands ###
