/**
 * 🦊 ADR System Vitest Configuration
 * Generated from the vitest-config-generator architecture
 * 
 * This configuration matches the structure generated by the vitest-config-generator
 * for the packages/dev-tools/adr-system project.
 */

import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "happy-dom",
    globals: true,
    include: ["src/**/*.{test,spec}.{js,ts,tsx}"],
    exclude: [
      "node_modules",
      "dist",
      "build",
      "coverage"
    ],
    setupFiles: ["./src/__tests__/setup.ts"],
    coverage: {
      provider: "v8",
      reporter: ["text", "json", "html"],
      reportsDirectory: ".vitest-coverage",
      thresholds: {
        global: {
          branches: 80,
          functions: 85,
          lines: 85,
          statements: 85,
        },
      },
    },
    reporters: ["default", "json"],
    outputFile: {
      json: ".vitest-reports/test-results.json",
    },
  },
});
