#!/usr/bin/env python3
"""
Reynard Name Pools
==================

Contains all animal spirit name collections and mythological references
for the Reynard robot name generator.

This module provides organized collections of names for different animal spirits,
mythological references, and naming conventions.
"""


class AnimalSpiritPools:
    """Collections of animal spirit names organized by species and themes."""

    def __init__(self) -> None:
        self.animal_spirits = {
            # Canines and Foxes
            "fox": [
                # Scientific and Latin
                "Vulpine",
                "Vulpes",
                "Fennec",
                "Arctic",
                "Kit",
                "Swift",
                "Cunning",
                # Mythological and Cultural
                "Reynard",
                "Kitsune",
                "Vixen",
                "Trickster",
                "Sly",
                "Wily",
                "Guile",
                "Slick",
                "Rascal",
                "Bandit",
                "Mischief",
                "Zorro",
                "Sage",
                "Clever",
                "Wit",
                "Crafty",
                "Shrewd",
                "Astute",
                "Sharp",
                "Bright",
                "Quick",
                # Color and Appearance
                "Rusty",
                "Amber",
                "Crimson",
                "Scarlet",
                "Copper",
                "Ginger",
                "Auburn",
                "Flame",
                "Ember",
                "Blaze",
                "Fire",
                "Sunset",
                "Autumn",
                "Maple",
                "Cedar",
                "Fern",
                "Willow",
                # Nature and Environment
                "Forest",
                "Woodland",
                "Meadow",
                "Prairie",
                "Desert",
                "Tundra",
                "Taiga",
                "Steppe",
                "Savanna",
                "Brush",
                "Thicket",
                "Grove",
                "Copse",
                "Glade",
                "Dell",
                "Vale",
                # Personality and Traits
                "Foxy",
                "Sneaky",
                "Elusive",
                "Graceful",
                "Agile",
                "Nimble",
                "Fleet",
                "Spry",
                "Lithe",
                "Supple",
                "Elegant",
                "Refined",
                "Sophisticated",
                "Charming",
                "Enchanting",
                "Alluring",
                "Captivating",
                "Mesmerizing",
                "Bewitching",
                "Spellbinding",
            ],
            "wolf": [
                # Scientific and Latin
                "Lupus",
                "Canis",
                "Lycan",
                "Lobo",
                "Lupin",
                # Mythological and Cultural
                "Fenrir",
                "Amaruq",
                "Phelan",
                "Conan",
                "Ragnar",
                "Akela",
                "Anuk",
                "Lobo",
                "Lupin",
                "Ralph",
                # Pack and Hierarchy
                "Alpha",
                "Beta",
                "Gamma",
                "Pack",
                "Leader",
                "Chief",
                "Captain",
                "Commander",
                "General",
                "Marshal",
                "Patriarch",
                "Matriarch",
                "Elder",
                "Wise",
                "Sage",
                # Hunting and Predator
                "Hunter",
                "Predator",
                "Stalker",
                "Tracker",
                "Scout",
                "Sentinel",
                "Guardian",
                "Protector",
                "Defender",
                "Warrior",
                "Fighter",
                "Champion",
                "Gladiator",
                "Knight",
                "Paladin",
                # Nature and Environment
                "Shadow",
                "Storm",
                "Midnight",
                "Blaze",
                "Fang",
                "Claw",
                "Tooth",
                "Talon",
                "Timber",
                "Ash",
                "River",
                "Stone",
                "Forest",
                "Mountain",
                "Valley",
                "Ridge",
                "Peak",
                "Summit",
                "Crest",
                "Aspen",
                "Sierra",
                "Dakota",
                "Raven",
                "Luna",
                "Moon",
                "Star",
                "Night",
                "Dawn",
                "Dusk",
                "Twilight",
                "Aurora",
                "Eclipse",
                # Personality and Traits
                "Fierce",
                "Wild",
                "Free",
                "Proud",
                "Noble",
                "Majestic",
                "Regal",
                "Royal",
                "Imperial",
                "Sovereign",
                "Dominant",
                "Powerful",
                "Strong",
                "Mighty",
                "Brave",
                "Bold",
                "Courageous",
                "Fearless",
                "Valiant",
                "Heroic",
                "Loyal",
                "Faithful",
                "Devoted",
                "Steadfast",
                "Resolute",
                "Determined",
                "Persistent",
                "Tenacious",
                "Relentless",
                "Unwavering",
            ],
            "otter": [
                # Scientific and Latin
                "Lutra",
                "Enhydra",
                "Pteronura",
                "Aonyx",
                "Lontra",
                # Literature and Media
                "Tarka",
                "Emmet",
                "Ollie",
                "Ottilie",
                "Otis",
                "Otty",
                # Playful and Cute
                "Bubbles",
                "Squirt",
                "Nibbles",
                "Puddle",
                "Wiggles",
                "Splash",
                "Ripple",
                "Pebbles",
                "Snickers",
                "Cuddles",
                "Snuggles",
                "Whiskers",
                "Fuzzy",
                "Dabble",
                "Splish",
                "Splash",
                "Drip",
                "Drop",
                "Trickle",
                "Stream",
                # Water and Aquatic
                "River",
                "Sea",
                "Brook",
                "Marina",
                "Aqua",
                "Wave",
                "Current",
                "Tide",
                "Flow",
                "Creek",
                "Stream",
                "Rapids",
                "Falls",
                "Cascade",
                "Fountain",
                "Spring",
                "Well",
                "Pool",
                "Pond",
                "Lake",
                "Bay",
                "Cove",
                "Harbor",
                "Delta",
                "Estuary",
                "Marsh",
                "Wetland",
                "Swamp",
                "Bog",
                "Fen",
                # Personality and Traits
                "Playful",
                "Joyful",
                "Cheerful",
                "Merry",
                "Happy",
                "Jolly",
                "Lively",
                "Vibrant",
                "Energetic",
                "Spirited",
                "Bubbly",
                "Effervescent",
                "Animated",
                "Dynamic",
                "Active",
                "Agile",
                "Nimble",
                "Graceful",
                "Sleek",
                "Smooth",
                "Fluid",
                "Elegant",
                "Charming",
                "Endearing",
                "Adorable",
                "Cute",
                "Sweet",
                "Gentle",
                "Kind",
                "Friendly",
                "Social",
                "Gregarious",
                "Outgoing",
                "Curious",
                "Inquisitive",
                "Explorer",
                "Adventurer",
                "Discoverer",
                "Seeker",
                "Wanderer",
                "Traveler",
                "Navigator",
                "Pilot",
                "Captain",
                "Skipper",
                "Mate",
                "Crew",
                "Team",
                "Squad",
                "Gang",
                "Band",
                "Group",
                "Flock",
                "Pod",
                "Colony",
                "Family",
                "Clan",
                "Tribe",
                "Community",
            ],
            # Additional animal spirits (abbreviated for space)
            "coyote": ["Canis", "Prairie", "Brush", "Desert", "Trickster", "Wily"],
            "jackal": ["Canis", "Golden", "Black", "Side", "Desert", "Stealth"],
            "dolphin": [
                "Delphinus",
                "Tursiops",
                "Orca",
                "Bottlenose",
                "Spinner",
                "Risso",
            ],
            "whale": [
                "Balaena",
                "Megaptera",
                "Physeter",
                "Orcinus",
                "Humpback",
                "Sperm",
            ],
            "shark": [
                "Carcharodon",
                "Galeocerdo",
                "Sphyrna",
                "Great",
                "Hammer",
                "Tiger",
            ],
            "octopus": [
                "Octopus",
                "Cephalopod",
                "Ink",
                "Tentacle",
                "Camouflage",
                "Intelligence",
            ],
            "axolotl": [
                "Ambystoma",
                "Axolotl",
                "Regen",
                "Mexican",
                "Salamander",
                "Neotenic",
            ],
            "eagle": ["Aquila", "Haliaeetus", "Golden", "Bald", "Harpy", "Crowned"],
            "falcon": ["Falco", "Peregrine", "Kestrel", "Merlin", "Gyrfalcon", "Saker"],
            "raven": ["Corvus", "Raven", "Crow", "Intelligence", "Mystery", "Omen"],
            "owl": ["Bubo", "Strix", "Tyto", "Barn", "Snowy", "Great", "Horned"],
            "hawk": ["Accipiter", "Buteo", "Red", "Cooper", "Sharp", "Broad"],
            "lion": ["Panthera", "Leo", "King", "Mane", "Pride", "Regal"],
            "tiger": ["Panthera", "Tigris", "Bengal", "Siberian", "Striped", "Fierce"],
            "leopard": ["Panthera", "Pardus", "Spotted", "Stealth", "Agile", "Climber"],
            "jaguar": ["Panthera", "Onca", "Amazon", "Powerful", "Spotted", "Hunter"],
            "cheetah": ["Acinonyx", "Jubatus", "Speed", "Spotted", "Fast", "Graceful"],
            "lynx": ["Lynx", "Bobcat", "Ear", "Tufted", "Stealth", "Mountain"],
            "bear": ["Ursus", "Grizzly", "Polar", "Black", "Brown", "Kodiak"],
            "panda": ["Ailuropoda", "Giant", "Bamboo", "Black", "White", "Gentle"],
            "elephant": ["Elephas", "Loxodonta", "Tusker", "Memory", "Wise", "Gentle"],
            "rhino": [
                "Rhinoceros",
                "Horn",
                "Armored",
                "Massive",
                "Ancient",
                "Powerful",
            ],
            "ape": [
                "Pan",
                "Gorilla",
                "Orangutan",
                "Chimpanzee",
                "Bonobo",
                "Intelligence",
            ],
            "monkey": ["Macaca", "Capuchin", "Spider", "Howler", "Marmoset", "Agile"],
            "lemur": ["Lemur", "Ring", "Sifaka", "Aye", "Aye", "Madagascar"],
            "snake": ["Serpens", "Python", "Cobra", "Viper", "Constrictor", "Venom"],
            "lizard": ["Lacerta", "Gecko", "Iguana", "Monitor", "Chameleon", "Dragon"],
            "turtle": ["Testudo", "Tortoise", "Shell", "Ancient", "Wise", "Slow"],
            "frog": ["Rana", "Tree", "Poison", "Dart", "Leap", "Amphibian"],
            "spider": ["Aranea", "Tarantula", "Web", "Silk", "Venom", "Eight"],
            "ant": ["Formica", "Colony", "Worker", "Queen", "Soldier", "Hive"],
            "bee": ["Apis", "Honey", "Queen", "Worker", "Drone", "Hive"],
            "mantis": ["Mantis", "Praying", "Preying", "Stealth", "Patience", "Strike"],
            "dragonfly": ["Odonata", "Dragon", "Fly", "Wing", "Agile", "Predator"],
            "pangolin": ["Manis", "Scaly", "Anteater", "Armored", "Unique", "Rare"],
            "platypus": [
                "Ornithorhynchus",
                "Duck",
                "Bill",
                "Venom",
                "Unique",
                "Australian",
            ],
            "narwhal": ["Monodon", "Unicorn", "Tusk", "Arctic", "Mystical", "Whale"],
            "quokka": [
                "Setonix",
                "Smile",
                "Happy",
                "Marsupial",
                "Australian",
                "Friendly",
            ],
            "capybara": ["Hydrochoerus", "Giant", "Rodent", "Water", "Social", "Calm"],
            "aye": ["Daubentonia", "Aye", "Aye", "Madagascar", "Nocturnal", "Unique"],
            "kiwi": ["Apteryx", "Flightless", "New", "Zealand", "Nocturnal", "Unique"],
            "toucan": ["Ramphastos", "Beak", "Colorful", "Tropical", "Fruit", "Bright"],
            "flamingo": [
                "Phoenicopterus",
                "Pink",
                "Flamingo",
                "Graceful",
                "Standing",
                "Elegant",
            ],
            "peacock": [
                "Pavo",
                "Peacock",
                "Feather",
                "Display",
                "Colorful",
                "Majestic",
            ],
        }

    def get_spirit_names(self, spirit: str) -> list[str]:
        """Get names for a specific animal spirit."""
        return self.animal_spirits.get(spirit, [])

    def get_all_spirits(self) -> list[str]:
        """Get list of all available animal spirits."""
        return list(self.animal_spirits.keys())

    def get_spirit_count(self, spirit: str) -> int:
        """Get the number of names available for a spirit."""
        return len(self.animal_spirits.get(spirit, []))


class MythologicalReferences:
    """Collections of mythological and cultural references."""

    def __init__(self) -> None:
        self.references = [
            # Greek/Roman
            "Atlas",
            "Prometheus",
            "Vulcan",
            "Minerva",
            "Apollo",
            "Artemis",
            "Odysseus",
            "Achilles",
            "Hector",
            "Perseus",
            "Theseus",
            "Orion",
            "Hercules",
            "Jason",
            "Bellerophon",
            "Cadmus",
            "Ares",
            "Athena",
            "Hera",
            "Zeus",
            "Poseidon",
            "Hades",
            "Dionysus",
            "Hermes",
            "Hephaestus",
            "Aphrodite",
            "Demeter",
            "Persephone",
            # Norse
            "Odin",
            "Thor",
            "Loki",
            "Freyja",
            "Freyr",
            "Tyr",
            "Heimdall",
            "Baldr",
            "Vidar",
            "Vali",
            "Fenrir",
            "Jormungandr",
            "Hel",
            "Sleipnir",
            "Gullinbursti",
            "Huginn",
            "Muninn",
            "Geri",
            "Freki",
            # Egyptian
            "Ra",
            "Anubis",
            "Horus",
            "Isis",
            "Osiris",
            "Set",
            "Thoth",
            "Bastet",
            "Sekhmet",
            "Hathor",
            "Ptah",
            "Sobek",
            "Khnum",
            "Maat",
            "Nephthys",
            "Geb",
            "Nut",
            "Shu",
            "Tefnut",
            # Celtic
            "Cernunnos",
            "Brigid",
            "Lugh",
            "Morrigan",
            "Dagda",
            "Aengus",
            "Manannan",
            "Bran",
            "Rhiannon",
            "Cerridwen",
            "Taliesin",
            "Arawn",
            "Pwyll",
            "Gwydion",
            "Arianrhod",
            "Lleu",
            "Blodeuwedd",
            "Math",
            "Don",
            "Gofannon",
            "Dylan",
            "Epona",
            "Sucellus",
            "Nantosuelta",
            "Taranis",
            "Esus",
            "Teutates",
            "Lugus",
            "Belenus",
            "Grannus",
            "Sirona",
            "Rosmerta",
            # Japanese
            "Amaterasu",
            "Susanoo",
            "Tsukuyomi",
            "Raijin",
            "Fujin",
            "Inari",
            "Benzaiten",
            "Bishamonten",
            "Daikokuten",
            "Hotei",
            "Jurojin",
            "Fukurokuju",
            "Ebisu",
            "Kannon",
            "Jizo",
            "Fudo",
            "Aizen",
            "Kitsune",
            "Tanuki",
            "Tengu",
            "Oni",
            "Yuki",
            "Kappa",
            "Nekomata",
            "Bakeneko",
            "Kodama",
            "Shinigami",
            "Yokai",
            "Kami",
            "Ryujin",
            "Orochi",
            "Yamata",
            "Kusanagi",
            "Ame",
            "No",
            "Habakiri",
            "Totsuka",
            "Kagutsuchi",
            "Izanagi",
            "Izanami",
            "Ninigi",
            "Hoori",
            "Yamasachi",
            "Umisachi",
            "Toyotama",
            "Otohime",
            "Urashima",
            "Momotaro",
            "Kintaro",
            "Issun",
            "Boshi",
            "Kaguya",
            "Hime",
            "Taketori",
            "Monogatari",
            # Hindu
            "Vishnu",
            "Shiva",
            "Brahma",
            "Krishna",
            "Rama",
            "Hanuman",
            "Ganesha",
            "Kali",
            "Durga",
            "Lakshmi",
            "Saraswati",
            "Indra",
            "Agni",
            "Varuna",
            "Vayu",
            "Surya",
            "Chandra",
            "Yama",
            # Chinese
            "Jade",
            "Emperor",
            "Dragon",
            "King",
            "Phoenix",
            "Tiger",
            "Turtle",
            "Snake",
            "Monkey",
            "Rooster",
            "Dog",
            "Pig",
            "Rat",
            "Ox",
            "Rabbit",
            "Horse",
            "Goat",
            "Zodiac",
        ]

    def get_references(self) -> list[str]:
        """Get all mythological references."""
        return self.references.copy()

    def get_reference_count(self) -> int:
        """Get the number of mythological references."""
        return len(self.references)
