import { it, expect } from 'vitest';
import {
  expectComponentToRender,
  expectComponentToThrow,
  expectPromiseToResolve,
  expectPromiseToReject,
  expectFunctionToBeCalledWith,
  expectFunctionToBeCalledTimes,
  expectFunctionNotToBeCalled,
  expectFunctionToBeCalled,
  expectValueToBeInRange,
  expectValueToBeApproximately,
  expectArrayToContain,
  expectArrayToHaveLength,
  expectObjectToHaveProperties,
  expectObjectToHaveValues,
  expectStringToMatch,
  expectStringToContain,
  expectElementToHaveAttributes,
  expectElementToHaveClasses,
  expectElementToHaveTextContent,
  expectElementToBeVisible,
  expectElementToBeHidden,
  expectElementToBeInTheDocument,
  expectElementNotToBeInTheDocument,
  expectElementToBeDisabled,
  expectElementToBeEnabled,
  expectElementToBeRequired,
  expectElementNotToBeRequired,
  expectElementToBeValid,
  expectElementToBeInvalid,
  expectElementToHaveFocus,
  expectElementNotToHaveFocus,
  expectElementToBeChecked,
  expectElementNotToBeChecked,
  expectElementToBePartiallyChecked,
  expectElementToHaveRole,
  expectElementToHaveAccessibleName,
  expectElementToHaveAccessibleDescription,
} from '../index';

export function testAssertionExports() {
  it('should export all assertion utilities', () => {
    expect(expectComponentToRender).toBeDefined();
    expect(expectComponentToThrow).toBeDefined();
    expect(expectPromiseToResolve).toBeDefined();
    expect(expectPromiseToReject).toBeDefined();
    expect(expectFunctionToBeCalledWith).toBeDefined();
    expect(expectFunctionToBeCalledTimes).toBeDefined();
    expect(expectFunctionNotToBeCalled).toBeDefined();
    expect(expectFunctionToBeCalled).toBeDefined();
    expect(expectValueToBeInRange).toBeDefined();
    expect(expectValueToBeApproximately).toBeDefined();
    expect(expectArrayToContain).toBeDefined();
    expect(expectArrayToHaveLength).toBeDefined();
    expect(expectObjectToHaveProperties).toBeDefined();
    expect(expectObjectToHaveValues).toBeDefined();
    expect(expectStringToMatch).toBeDefined();
    expect(expectStringToContain).toBeDefined();
    expect(expectElementToHaveAttributes).toBeDefined();
    expect(expectElementToHaveClasses).toBeDefined();
    expect(expectElementToHaveTextContent).toBeDefined();
    expect(expectElementToBeVisible).toBeDefined();
    expect(expectElementToBeHidden).toBeDefined();
    expect(expectElementToBeInTheDocument).toBeDefined();
    expect(expectElementNotToBeInTheDocument).toBeDefined();
    expect(expectElementToBeDisabled).toBeDefined();
    expect(expectElementToBeEnabled).toBeDefined();
    expect(expectElementToBeRequired).toBeDefined();
    expect(expectElementNotToBeRequired).toBeDefined();
    expect(expectElementToBeValid).toBeDefined();
    expect(expectElementToBeInvalid).toBeDefined();
    expect(expectElementToHaveFocus).toBeDefined();
    expect(expectElementNotToHaveFocus).toBeDefined();
    expect(expectElementToBeChecked).toBeDefined();
    expect(expectElementNotToBeChecked).toBeDefined();
    expect(expectElementToBePartiallyChecked).toBeDefined();
    expect(expectElementToHaveRole).toBeDefined();
    expect(expectElementToHaveAccessibleName).toBeDefined();
    expect(expectElementToHaveAccessibleDescription).toBeDefined();
  });
}
